core/urls.py
from django.urls import path, include

from .views import SignupView

app_name = "core"
urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
# import debug_toolbar
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('core/', include('core.urls', namespace='core')),
    path('search/', include('search.urls', namespace='search')),
    path('', views.home, name='home'),
    # path('', include('pages.urls')),
    # path('signup/', views.signup, name="signup"),
]

search/urls.py
from django.urls import path

from . import views


app_name = "search"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:product_code>/", views.detail, name="detail"),
    path("swap/<int:product_code>/", views.swap, name="swap"),
    path("remove/<int:product_code>/", views.remove_substitute, name="remove"),
    path("list_products/", views.list_products, name="list_products"),
    path(
        "add_substitute/<int:product_code>/<int:subs_id>/",
        views.add_substitute,
        name="add_substitute",
    ),
    path("mentions_legales/", views.mentions, name="mentions"),
]

search/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.


class Product(models.Model):

    def __str__(self):
        return self.product_name.capitalize()

    # We specify the model fields
    product_name = models.CharField(max_length=100)
    brands = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=200, null=True)
    product_url = models.CharField(max_length=150, null=True)
    product_code = models.BigIntegerField(null=False, primary_key=True)
    product_image = models.CharField(max_length=100, null=True)
    nutriscore = models.CharField(max_length=1, null=True)
    stores = models.CharField(max_length=150, null=True)
    quantity = models.CharField(max_length=40, null=True)
    nova_groups = models.CharField(max_length=5, null=True)
    categories = models.CharField(max_length=500, null=True)
    substitutes = models.ManyToManyField("self")
    fat_100g = models.CharField(max_length=20, null=True)
    saturated_fat_100g = models.CharField(max_length=20, null=True)
    sugars_100g = models.CharField(max_length=20, null=True)
    salt_100g = models.CharField(max_length=20, null=True)
    

search/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from search.search_form import SearchForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from stop_words import get_stop_words
from django.db.models import Q
from random import randrange

from .models import Product
from core.models import CustomUser

# Create your views here.


def index(request):
    if request.method == "POST":
        print("post")
        return render(request, "search/index.html")
    else:        
        form = SearchForm(request.GET)
        request.session['latitude'] = request.GET.get('latitude')
        request.session['longitude'] = request.GET.get('longitude')
        if form.is_valid():
            data = form.cleaned_data["post"].casefold()
            stop_words = get_stop_words("fr")
            splited_search = data.split(" ")            
            resulting_search = list(set(splited_search) - set(stop_words))

            db_res = words_filter(resulting_search)            
            paginator = Paginator(db_res, 12)
            page = request.GET.get('page')            
            result = paginator.get_page(page)            
            # res = [i for i in db_res]
            context = {"form": form, "res": result}
            return render(request, "search/index.html", context)
        else:            
            form = SearchForm()
            return render(request, "search/index.html", {"form": form})


def words_filter(resulting_search):
    """ filter the number of words in search with AND """

    if len(resulting_search) < 2:
        result = Product.objects.filter(product_name__contains=resulting_search[0]).order_by('product_code')
        return result
    elif len(resulting_search) < 3:
        result = Product.objects.filter(
            product_name__contains=resulting_search[0]
        ).filter(product_name__contains=resulting_search[1])
        return result
    elif len(resulting_search) < 4:
        result = (
            Product.objects.filter(product_name__contains=resulting_search[0])
            .filter(product_name__contains=resulting_search[1])
            .filter(product_name__contains=resulting_search[2])
        )
        return result
    elif len(resulting_search) < 5:
        result = (
            Product.objects.filter(product_name__contains=resulting_search[0])
            .filter(product_name__contains=resulting_search[1])
            .filter(product_name__contains=resulting_search[2])
            .filter(product_name__contains=resulting_search[3])
        )
        return result


def detail(request, product_code):
    # product = get_object_or_404(Product, pk=product_code)
    product = Product.objects.get(product_code=product_code)
    splited_stores = product.stores.split(",")
    json_data = {
        "product": product,
        "code": product.product_code,
        "nova_groups": product.nova_groups,
        "categories": product.categories,
        "stores": splited_stores,
        "nutriscore": product.nutriscore.capitalize(),
        "image": product.product_image,
        "fat_100g": product.fat_100g,
        "salt_100g": product.salt_100g,
        "saturated_fat_100g": product.saturated_fat_100g,
        "sugars_100g": product.sugars_100g,
    }
    return render(request, "search/detail.html", json_data)


def mentions(request):
    return render(request, "search/mentions_legales.html")


def swap(request, product_code):
    """
    get categories form request
    search database for products matching all categories
    and with nutriscore corresponding to A
    display food product
    """

    product = get_object_or_404(Product, pk=product_code)
    splited = product.categories.split(",")
    # trick to avoid products with less than 3 categories
    if len(splited) < 3:
        splited.append(" x")

    categories_res = (
        Product.objects.filter(categories__contains=splited[0])
        .filter(categories__contains=splited[1])
        .filter(categories__contains=splited[2])
        .filter(nutriscore__lt=product.nutriscore)
    )  # order_by(?) + slice sur le 1er
    # print(categories_res)
    # print(product.nutriscore)
    arr = []
    for x in categories_res:
        z = compare_products(x, product)
        if z is not None:
            arr.append(z)

    if bool(arr) is False:
        substitute = product
        json_data = {
            "product": substitute,
            "code": substitute.product_code,
            "nova_groups": substitute.nova_groups,
            "categories": substitute.categories,
            "nutriscore": substitute.nutriscore.capitalize(),
            "image": substitute.product_image,
            "fat_100g": product.fat_100g,
            "salt_100g": product.salt_100g,
            "saturated_fat_100g": product.saturated_fat_100g,
            "sugars_100g": product.sugars_100g,
            "status": "Pas de meilleur produit trouvé !",
            "id": product_code,
        }
    else:
        substitute = arr[randrange(len(arr))][
            0
        ]  # select substitute randomly among all better products
        # print(substitute.product_code)
        json_data = {
            "product": substitute,
            "code": substitute.product_code,
            "nova_groups": substitute.nova_groups,
            "categories": substitute.categories,
            "nutriscore": substitute.nutriscore.capitalize(),
            "image": substitute.product_image,
            "fat_100g": product.fat_100g,
            "salt_100g": product.salt_100g,
            "saturated_fat_100g": product.saturated_fat_100g,
            "sugars_100g": product.sugars_100g,
            "status": "",
            "id": product_code,
        }

    return render(request, "search/swap.html", json_data)


def compare_products(x, y):
    """ compare nutriscores to return better product"""

    abc = ["a", "b", "c", "d", "e", "f", "g"]
    # if x location's index in abc is lower than y location's index then...
    better = abc.index(x.nutriscore)
    original = abc.index(y.nutriscore)

    if better < original:
        # print("better product")
        return x, x.product_code


@login_required
def list_products(request):
    current_user = request.user

    context = get_substitutes(current_user)

    return render(request, "search/list_products.html", context)


# @login_required
def add_substitute(request, product_code, subs_id):

    current_user = request.user

    # add current substitute to current_user using fk relation
    # product_to_associate = Product.objects.get(id=product_code)  # to delete
    user_to_associate = CustomUser.objects.get(email=current_user)
    user_to_associate.user_substitutes.add(subs_id)

    context = get_substitutes(current_user)

    return render(request, "search/list_products.html", context)


# @login_required
def get_substitutes(current_user):
    # redirect to substitute list of connected user
    substitutes_list = CustomUser.objects.filter(user_substitutes__isnull=False).filter(
        email=current_user
    )

    if not substitutes_list:
        return None
    else:
        main_sub_list = [i for i in substitutes_list]
        sub_list = [j for j in main_sub_list[0].user_substitutes.all()]

        context = {"full_list": sub_list}

        return context


# @login_required
def remove_substitute(request, product_code):

    current_user = request.user

    user_to_associate = CustomUser.objects.get(email=current_user)
    user_to_associate.user_substitutes.remove(product_code)

    context = get_substitutes(current_user)

    return render(request, "search/list_products.html", context)

search/templates/search/detail.html
{% extends 'base.html' %}

{% block first_row %}
<div style="background-color: chocolate; padding: 10 20 10 20;opacity:0.85;" class="rounded">
<h1 style="-webkit-text-fill-color: white;">Détails du produit</h1>
</div>

  <div class="row first_row_window rounded">
		<div class="col-md-8">
			<h3>
				{{ product }}
			</h3>

			<dl>
				<dt>Product code :</dt>
				<dd>{{ code }}</dd>
				<br>
				<dt>
					Nutriscore :
				</dt>
				<dd>
					{{ nutriscore }}
				</dd>
				<br>			
				<dt>
					Novagroup :
				</dt>
				<dd>
					{{ nova_groups }}
				</dd>
				<br>
				<dt>
					Categories :
				</dt>
				<dd>
					{{ categories }}
				</dd>
				<br>
				<br>
				<dt>
					Sel (pour 100gr) :
				</dt>
				<dd>
					{{ salt_100g }} gr
				</dd>
				<br>
				<dt>
					Matières grasses / Lipides (pour 100gr) :
				</dt>
				<dd>
					{{ fat_100g }} gr
				</dd>
				<br>
				<dt>
					Graisses saturées (pour 100gr) :
				</dt>
				<dd>
					{{ saturated_fat_100g }} gr
				</dd>
				<br>
				<dt>
					Sucres (pour 100gr) :
				</dt>
				<dd>
					{{ sugars_100g }} gr
				</dd>
				<br>
				<dt>
					Disponible dans les magasins :
				</dt>
				<br>				
	  </dl> 

	  {% if stores %}
	  
	  <div class="btn-group" role="group" aria-label="Basic example" style="margin-bottom: 20px;">
		{% for store in stores %}
		
		<button type="button" class="btn btn-outline-primary" id="poplink" href="#" 
			target="popup" 
			onclick='
			var lat = sessionStorage.getItem("lat");
		  	var lon = sessionStorage.getItem("lon");
			window.open("https://www.google.com/maps/search/{{ store }}/@"+lat+","+lon+",12z/data=!3m1!4b1","popup","width=1200,height=800"); return false;'>
			{{ store }}
		</button>

		{% endfor %}
	  </div>

	  {% endif %}

	  

<div>
	  <a class="btn btn-warning" href="{% url 'search:swap' code %}" role="button">Substituer</a>
	  <!-- /search/swap/{{product.id}}  -->
</div>
		</div>
		<div class="col-md-4 ml 4">
			<img alt="{{ product }}" src="{{ image }}" class="img-fluid rounded" />
		</div>
	</div>

{% endblock %}

search/templates/search/index.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}



{% block first_row %}

<div style="background-color: #345A61; padding: 40 40 20 40; opacity: 0.80;" class="rounded">

    {% if user.is_authenticated %}
    <h1 style="color:white">Du gras oui, mais de qualité !</h1>
    <h3 style="color:white">{{user.email}}, trouvez un produit de substitution pour ceux que vous consommez tous les
        jours</h3>
    {% else %}
    <h1 style="color:white">Du gras oui, mais de qualité !</h1>
    <h3 style="color:white">Cher(e) visiteur(euse), trouvez un produit de substitution pour ceux que vous consommez tous
        les jours </h3>
    {% endif %}

</div>



<form method="get" class="form-inline justify-content-center search_container rounded" style="margin-top: 80px"
    novalidate>
    {% csrf_token%}
    {{ form|crispy }}
    <button class="btn btn-primary ml-4" type="submit">Chercher</button>
</form>

{% if res %}

<div class="row first_row_window rounded">


    {% for product in res %}

    <div class="col-sm-6 col-md-4 col-lg-3 mt-4">
        <div class="card card-inverse card-info border-dark">
            <img class="card-img-top" src="{{ product.product_image }}">
            <img class="card-img-overlay" src="{% get_static_prefix %}core/{{ product.nutriscore }}.png" alt=""
                style="float: right; margin-top: -45px; margin-left: 195px;width: 90px;">
            <div class="card-block">
                <h5 class="card-title" style="height:50px;padding: 5 5 5 5;">{{ product.product_name|truncatechars:40 }}
                </h5>
            </div>
            <div class="card-footer">
                <a href="/search/{{ product.product_code }}/" class="btn btn-info btn-sm" role="button">Détails</a>
                <a href="{% url 'search:swap' product.product_code %}" class="btn btn-warning btn-sm" role="button">Substituer</a>
            </div>
        </div>
    </div>


    {% endfor %}

    {% else %}

    {% if request.method == 'POST' %}

    <div class="row first_row_window rounded">

        <div class="col-8 mt-4">
            <h4>Pas de produits trouvé !</h4>
        </div>
    </div>

    {% endif %}

    {% endif %}

    

    <div class="pagination">
        <span class="step-links">
            {% if res.has_previous %}
                <a href="?post={{ request.GET.post }}&page=1">&laquo; première</a>
                <a href="?post={{ request.GET.post }}&page={{ res.previous_page_number }}">précedente</a>
            {% endif %}
    
            {% if res.number %}
            <span class="current">
                Page {{ res.number }} sur {{ res.paginator.num_pages }}.
            </span>
            {% endif %}
    
            {% if res.has_next %}
                <a href="?post={{ request.GET.post }}&page={{ res.next_page_number }}">suivante</a>
                <a href="?post={{ request.GET.post }}&page={{ res.paginator.num_pages }}">dernière &raquo;</a>
            {% endif %}
        </span>
    </div>

   
    

</div>



{% endblock %}


{% block second_row %}

<div class="container-fluid" style="padding-left:40px;padding-right:40px;">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center" style="margin-top:40px;">
                Colette & Remy
            </h2>
            <h3 class="text-center">------</h3>
            <h3 class="bold">De la ratatouille aux croissants</h3>
            <p>
                Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que
                vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.
                <br>
                </br>
                <em>
                    <strong>Colette Tatou :</strong>"Nous aimons tous manger, surtout en France ! Personnellement, une
                    baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le
                    monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout
                    lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais
                    l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"
                    <br>
                    </br>
                    <strong>Remy :</strong> "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup
                    me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des
                    boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque
                    Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je
                    savais tout de suite où le trouver. L'idée de Pur Beurre était née !"
                </em>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <img alt="Ratatouille" src="{% static 'core/ratatouille-portrait.jpg' %}"
                style="height: 280px;margin-top: 200px;" class="float-right" />
        </div>
        <div class="col-md-6">
            <img alt="Colette" src="{% static 'core/colette-tatou-full.png' %}" />
        </div>

    </div>
</div>

{% endblock %}


{% block third_row %}

<div class="container-fluid" style="padding:40 40 40 40;">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center" style="color:white">
                Contactez-nous
            </h3>
            <p class="text-center" style="color:white">
                Nous sommes à votre disposition si vous avez la mondre question !
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="row justify-content-center" style="margin-top:20">
                <span style="font-size: 3em; color: white;">
                    <i class="fas fa-phone-alt"></i>
                </span>
            </div>
            <div class="row justify-content-center">
                <h4 style="color:white;margin-top:10">
                    06 05 04 03 02
                </h4>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row justify-content-center" style="margin-top:20">
                <span style="font-size: 3em; color: white;">
                    <i class="far fa-envelope"></i>
                </span>
            </div>
            <div class="row justify-content-center">
                <h4 style="color:white;margin-top:10">
                    contact@purbeurre.com
                </h4>
            </div>
        </div>
    </div>
</div>

{% endblock %}

search/templates/search/list_products.html
{% extends 'base.html' %}

{% block first_row %}

{% load static %}

<div style="background-color: chocolate; padding: 10 20 10 20;opacity:0.85;" class="rounded">
    <h1 style="-webkit-text-fill-color: white;">Vos produits favoris</h1>
</div>

<div class="row first_row_window rounded">

    {% if full_list %}

    {% for product in full_list %}

    <div class="col-sm-6 col-md-4 col-lg-3 mt-4">
        <div class="card card-inverse card-info border-success">
            <img class="card-img-top" src="{{ product.product_image }}">
            <img class="card-img-overlay" src="{% get_static_prefix %}core/{{ product.nutriscore }}.png" alt=""
                style="float: right; margin-top: -45px; margin-left: 195px;width: 90px;">
            <div class="card-block">
                <h5 class="card-title" style="height:50px;padding: 5 5 5 5;">{{ product.product_name|truncatechars:40 }}
                </h5>
            </div>
            <div class="card-footer">
                <a href="/search/{{ product.product_code }}/" class="btn btn-info btn-sm" role="button">Détails</a>
                <a href="{% url 'search:remove' product.product_code %}" class="btn btn-danger btn-sm" role="button">Retirer</a>
            </div>
        </div>
    </div>


    {% endfor %}

    {% else %}
    <p>Aucun produit n'est disponible</p>
    {% endif %}

</div>

{% endblock %}

search/templates/search/mentions_legales.html
{% extends 'base.html' %}

{% block first_row %}

<div class="first_row_window rounded">

    <h2>Mentions légales</h2>   

<h3>PRÉSENTATION</h3>    
Conformément à la loi n° 2004-2005 du 21 juin 2004 pour la confiance dans
l’économie numérique, notre site web créé met à disposition du public les
informations concernant notre société.
Les conditions suivantes s’appliquent à toute personne qui accède et utilise le site
web, les contenus et services qui y sont associés.
Eventuellement modifiables, nous vous invitons donc à consulter nos mentions
légales le plus souvent possible, de manière à en prendre connaissance
fréquemment.

<h3>EDITEUR</h3>  
Le site www.travelshop.fr appartient à la société ANTIDOTS GROUP dont le siège
est situé à l’adresse suivante : 16 avenue Victoria – 73 100 Aix-les-Bains – France.
Le Directeur de la publication : Mme S. Favier, en qualité Responsable
Communication
Courriel : contact@travelshop.fr
Tél : 0 811 480 470

<h3>HÉBERGEUR</h3> 
Le site www.travelshop.fr est hébergé par OVH, dont le siège est situé à l’adresse
suivante : 2 rue Kellermann – 59100 Roubaix– France.
Courriel : hosting@ml.ovh.net
SITE WEB Travelshop.fr
Les informations fournies sur le site www.travelshop.fr sont uniquement destinées
à donner un aperçu général des produits et services d’ANTIDOTS GROUP, sans 
prétendre à l’exhaustivité. Avant de vous baser sur les informations fournies sur ce
site, vous devez les vérifier et/ou les compléter auprès d’ANTIDOTS GROUP.
ANTIDOTS GROUP ne pourra être tenue pour responsable de quelque manière
que ce soit des conséquences directes ou indirectes engendrées par des pertes, des
retards liés à l’utilisation du présent site web ou à l’impossibilité de l’utiliser.
Sur son site, Travelshop.fr propose des liens vers d’autres sites. ANTIDOTS
GROUP n’exerce aucun contrôle sur les sites web autre que le sien et n’assume
aucune responsabilité concernant ces sites ou leurs contenus.
ANTIDOTS GROUP ne garantit pas l’absence d’erreurs typographiques,
d’imprécisions ou d’inexactitudes techniques sur le site. ANTIDOTS GROUP ne
garantit pas l’exactitude des informations publiées. Il vous appartient de vérifier
auprès d’ANTIDOTS GROUP les informations avant de prendre des décisions
relatives aux services, produits ou autres, décrits dans ce site web.

<h3>PROTECTION DES DONNÉES PERSONNELLES</h3> 
ANTIDOTS GROUP est susceptible de collecter et traiter des données à caractère
personnel des visiteurs de son site Internet, en tant que Responsable de Traitement,
au sens de la Loi n° 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers
et aux libertés modifiée. Cette loi est désignée dans la suite des présentes mentions
légales par le terme « Loi Informatique et Libertés ».
Par données à caractère personnel, nous entendons, conformément à la Loi
Informatique et Libertés, toute information relative à une personne physique
identifiée ou qui peut être identifiée, directement ou indirectement, par référence à
un numéro d’identification ou à un ou plusieurs éléments qui lui sont propres.
ANTIDOTS GROUP est attaché au respect et à la protection de la vie privée. Il
s’engage à définir et appliquer les mesures adéquates afin de garantir la sécurité de
vos données personnelles. Afin de veiller à la bonne application de ces règles,
ANTIDOTS GROUP a désigné un Correspondant Informatique et Libertés (CIL)
qui est le relais privilégié avec la Commission Nationale de l’Informatique et des
Libertés (CNIL).

<h3> UTILISATION FAITE DES DONNÉES</h3>
Les données à caractère personnel recueillies via le site Internet Travelshop.fr, le
sont dans le but d’assurer les services d’ANTIDOTS GROUP, notamment :
• pour répondre à vos demandes exprimées via les formulaires ou en utilisant
les moyens de contact disponibles sur le site Internet Travelshop.fr,
• pour vous contacter au sujet d’enquêtes de satisfaction ou d’études de
marché,
• dans un objectif commercial si vous nous y avez autorisés,
• pour personnaliser votre interaction avec nos sites, faciliter votre navigation
et pour élaborer des statistiques d’utilisation du site Internet Travelshop.fr,
• pour une candidature à un poste au sein d’ANTIDOTS GROUP,
• pour développer un partenariat.
<h3>DESTINATAIRES DES DONNÉES</h3> 
Les données collectées sur le site Internet Travelshop.fr sont exclusivement
réservées à l’usage d’ANTIDOTS GROUP, et ne font l’objet d’aucune cession à
des tiers.
Afin de répondre au mieux à vos demandes et besoins (par exemple sélection de
l’offre de service la mieux adaptée, etc.), les données collectées peuvent
éventuellement être partagées aux filiales ou entités du Group.
<h3> SÉCURITÉ DES DONNÉES</h3>
ANTIDOTS GROUP s’engage à prendre toutes les précautions utiles afin de
préserver la sécurité et la confidentialité des données collectées en appliquant les
mesures techniques et organisationnelles adéquates.

<h3>COOKIES</h3> 
Afin d’optimiser et améliorer la qualité des services qui vous sont proposés et leur
adéquation avec vos attentes, ANTIDOTS GROUP est susceptible d’utiliser des «
cookies ».
En accédant au site Internet d’ANTIDOTS GROUP et en y poursuivant votre
navigation, vous fournissez votre accord à l’implémentation et l’utilisation de 
cookies sur votre terminal, et vous reconnaissez avoir pris connaissance de
l’information qui vous est fournie concernant l’utilisation de ces cookies, et des
moyens dont vous disposez notamment pour vous y opposer.
Pour plus d’informations sur l’utilisation de cookies par ANTIDOTS GROUP,
veuillez consulter notre Politique des Cookies.
CONSERVATION DES DONNÉES
Sauf règlementation spécifique applicable, ANTIDOTS GROUP conserve les
données personnelles collectées pendant la durée justifiée par la finalité de leur
traitement.
<h3> VOS DROITS AU REGARD DE LA LOI INFORMATIQUE ET LIBERTÉ</h3>
Conformément à la Loi Informatique et Libertés, vous disposez d’un droit d’accès,
de rectification et d’opposition aux données personnelles vous concernant.
Pour exercer ces droits, adressez-vous par courrier à ANTIDOTS GROUP – 16
avenue Victoria – 73 100 Aix-les-Bains
Conformément à la réglementation en vigueur, afin de justifier de votre identité,
votre demande doit être signée et accompagnée de la photocopie d’un titre
d’identité valide portant votre signature et préciser l’adresse à laquelle doit vous
parvenir la réponse.

<h3>DROIT DE PROPRIÉTÉ INTELLECTUELLE</h3> 
ANTIDOTS GROUP, le site 360timeline.com et son contenu (propre ou celui de
ses partenaires) sont protégés par le droit des marques et/ou le droit d’auteur et
autres droits. L’ensemble de ces éléments demeure la propriété exclusive
d’ANTIDOTS GROUP ou de ses partenaires. En application des dispositions du
Code de la propriété intellectuelle, des dispositions législatives et réglementaires de
tous pays et des conventions internationales, toute représentation et/ou
reproduction, ou encore utilisation, exploitation, intégrale ou partielle, de l’un 
quelconque des éléments mentionnés ci-dessus, faite sans le consentement
préalable et écrit d’ANTIDOTS GROUP ou de ses partenaires, est interdite.

</div>

{% endblock %}

search/templates/search/swap.html
{% extends 'base.html' %}

{% block first_row %}

<div style="background-color: cadetblue; padding: 10 20 10 20;opacity:0.85;" class="rounded">
	<h1 style="-webkit-text-fill-color: white;">Proposition de substitut</h1>
</div>

<div class="row first_row_window rounded">
	<div class="col-md-8">
		<h3>
			{{ product }}
		</h3>

		<p style="display:none">{{ product.product_code  }}</p>

		{%  if  status != "" %}
		<div class="alert alert-danger alert-dismissable">

			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
				×
			</button>
			<h4>
				Alerte Produit !
			</h4> {{ status }} <a href="#" class="alert-link"></a>
		</div>
		{% endif %}
		<dl>
			<dt>Product code :</dt>
			<dd>{{ code }}</dd>
			<br>
			<dt>
				Nutriscore :
			</dt>
			<dd>
				{{ nutriscore }}
			</dd>
			<br>
			<dt>
				Novagroup :
			</dt>
			<dd>
				{{ nova_groups }}
			</dd>
			<br>
			<dt>
				Categories :
			</dt>
			<dd>
				{{ categories }}
			</dd>
			<br>
			<br>
			<dt>
				Sel (pour 100gr) :
			</dt>
			<dd>
				{{ salt_100g }} gr
			</dd>
			<br>
			<dt>
				Matières grasses / Lipides (pour 100gr) :
			</dt>
			<dd>
				{{ fat_100g }} gr
			</dd>
			<br>
			<dt>
				Graisses saturées (pour 100gr) :
			</dt>
			<dd>
				{{ saturated_fat_100g }} gr
			</dd>
			<br>
			<dt>
				Sucres (pour 100gr) :
			</dt>
			<dd>
				{{ sugars_100g }} gr
			</dd>
			<br>
		</dl>


		{% if user.is_authenticated %}
		<a class="btn btn-secondary" href="{% url 'search:add_substitute' code  product.product_code %}" role="button">Ajouter aux
			Favoris</a>
		{% else %}
		<a class="btn btn-secondary"
			href="{% url 'account_login' %}?next={% url 'search:add_substitute' code  product.product_code %}" role="button">Ajouter
			aux Favoris</a>
		{% endif %}

	</div>
	<div class="col-md-4 ml 4">
		<img alt="{{ product }}" src="{{ image }}" class="img-fluid rounded" />
	</div>
</div>



{% endblock %}