core/urls.py
from django.urls import path, include

from .views import SignupView

app_name = "core"
urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
]

purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include
# import debug_toolbar
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('core/', include('core.urls', namespace='core')),
    path('search/', include('search.urls', namespace='search')),
    path('', views.home, name='home'),
    # path('', include('pages.urls')),
    # path('signup/', views.signup, name="signup"),
]

search/urls.py
from django.urls import path

from . import views


app_name = "search"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:product_code>/", views.detail, name="detail"),
    path("swap/<int:product_code>/", views.swap, name="swap"),
    path("remove/<int:product_code>/", views.remove_substitute, name="remove"),
    path("list_products/", views.list_products, name="list_products"),
    path(
        "add_substitute/<int:product_code>/<int:subs_id>/",
        views.add_substitute,
        name="add_substitute",
    ),
    path("mentions_legales/", views.mentions, name="mentions"),
]

core/models.py
from django.db import models
from search.models import Product

# Create your models here.

# from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=True)  # not null
    username = models.CharField(max_length=100, null=True)
    user_substitutes = models.ManyToManyField(Product)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. ''Unselect this instead of deleting accounts.'
        ),
    )

    USERNAME_FIELD = 'email'
    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.get_full_name()

    def __str__(self):
        return self.email

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from search.search_form import SearchForm
from django.views.generic.edit import FormView

# Create your views here.


def home(request):
    form = SearchForm()
    # return render(request, "search/index.html", {"form": form})
    return redirect("search/")


class SignupView(FormView):
    form_class = UserCreationForm
    template_name = "account/signup.html"

core/templates/base.html
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/40c6803a98.js"></script>  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    {% load static %}    
    <link rel="stylesheet" href="{% static 'core/custom-style.css' %}" type="text/css">
    <script src="{% static 'core/footer.js' %}"></script>
    <script src="{% static 'core/geolocation.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #C45525">
            <div class="container">
                <a class="navbar-brand" href="{% url 'search:index' %}"><img src="{% static 'core/logo_pur_beurre.png' %}" height=45px></a>
                <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> -->
            
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link main_title" style="color: white;" href="{% url 'search:index' %}">Pure Beurre<span class="sr-only">(current)</span></a>
                    </li>           
                                       
                    </ul>
                 
                </div>
                <form method="post" class="form-inline my-2 my-lg-0">
                 
                    {% if user.is_authenticated %}
                    <button class="btn btn-secondary mr-2 ml-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.email }}
                    </button>
                    
                    <a href="{% url 'search:list_products' %}"><img src="{% static 'core/noun_Carrot_29691_cropped.png' %}" height=50px title="Mes produits favoris"></a>
                    <a href="{% url 'account_logout' %}"><img src="{% static 'core/disconnect.png' %}" height=40px  class="ml-4" title="Se déconnecter"></a> 
                                     
                    <!-- <button class="btn btn-default ml-2">
                    <a class="btn btn-default" href="{% url 'account_logout' %}">Disconnect</a>
                    </button> -->
                    
                    {% else %}                      
                       <a class="btn btn-primary mr-4" href="{% url 'account_signup' %}">S'enregistrer</a>  
                       <a class="btn btn-primary" href="{% url 'account_login' %}">Connexion</a>                     
                    {% endif %}
                </form>                                      
                
            </div>
        </nav>


       


        <div class="container-fluid">

            <div class="row align-items-center">
                <div class="col-md-12 first_row_bg">
                    <div class="container ">
                    {% block first_row %}

                    {% endblock %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                {% block second_row %}

                {% endblock %}
                </div>
            </div>
            <div class="row" style="background-color: #C45525">
                <div class="col-md-12">
                {% block third_row %}

                {% endblock %}
                </div>
            </div>

           
            <!-- <div class="row" style="padding-top: 20">
                    
                <div class="col-md-6">
                    <p class="text-center">  <a href="{% url 'search:mentions' %}">Mentions légales</a></p> 
                </div>
                <div class="col-md-6">
                    <p class="text-center">Contact</p> 
                </div>
                    
            </div> -->

           
        </div>

        <footer class="row footer" id="footer">

            <div class="col-md-6">
                    <p class="text-center">  <a href="{% url 'search:mentions' %}">Mentions légales</a></p> 
                </div>
                <div class="col-md-6">
                    <p class="text-center">Contact</p> 
            </div>


        </footer>




</body>
</html>

core/templates/home.html
{% extends 'base.html' %}

{% block first_row %}

<h1> Home Page</h1>

{% endblock %}